spring.application.name=JopTrackerApp
server.port=8081
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/jobtracker
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.error.include-message=always